import type { Template } from "../types";
import { toKebabCase, toPascalCase } from "../utils";

function vars(v: Record<string, unknown>) {
  const name = String(v.name ?? "my-context");
  const id = toKebabCase(name);
  const className = toPascalCase(name) + "Context";
  const desc = String(v.description ?? "");
  return { name, id, className, desc };
}

export const contextTemplates: Template[] = [
  {
    name: "basic",
    description: "基础上下文 — 通用键值存储上下文",
    category: "context",
    variables: [
      { name: "name", description: "上下文名称", type: "string", required: true },
      { name: "description", description: "上下文描述", type: "string", default: "" },
    ],
    render(v) {
      const { name, id, className, desc } = vars(v);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            "export interface ContextMeta {",
            "  name: string;",
            "  description: string;",
            "  createdAt: number;",
            "}",
            "",
            `export class ${className} {`,
            "  readonly meta: ContextMeta;",
            "  private store = new Map<string, unknown>();",
            "",
            "  constructor() {",
            "    this.meta = {",
            `      name: "${name}",`,
            `      description: "${desc || name + " 上下文"}",`,
            "      createdAt: Date.now(),",
            "    };",
            "  }",
            "",
            "  get<T = unknown>(key: string): T | undefined {",
            "    return this.store.get(key) as T | undefined;",
            "  }",
            "",
            "  set(key: string, value: unknown): void {",
            "    this.store.set(key, value);",
            "  }",
            "",
            "  has(key: string): boolean {",
            "    return this.store.has(key);",
            "  }",
            "",
            "  delete(key: string): boolean {",
            "    return this.store.delete(key);",
            "  }",
            "",
            "  clear(): void {",
            "    this.store.clear();",
            "  }",
            "",
            "  keys(): string[] {",
            "    return Array.from(this.store.keys());",
            "  }",
            "",
            "  toJSON(): Record<string, unknown> {",
            "    return Object.fromEntries(this.store);",
            "  }",
            "}",
            "",
            `export default ${className};`,
            "",
          ].join("\n"),
        },
      ];
    },
  },

  {
    name: "conversation",
    description: "对话上下文 — 维护对话历史与角色状态",
    category: "context",
    variables: [
      { name: "name", description: "上下文名称", type: "string", required: true },
      { name: "description", description: "上下文描述", type: "string", default: "" },
      { name: "maxHistory", description: "最大历史记录数", type: "number", default: 100 },
    ],
    render(v) {
      const { name, id, className, desc } = vars(v);
      const maxHistory = Number(v.maxHistory ?? 100);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            "export type Role = \"system\" | \"user\" | \"assistant\" | \"tool\";",
            "",
            "export interface Message {",
            "  role: Role;",
            "  content: string;",
            "  timestamp: number;",
            "  metadata?: Record<string, unknown>;",
            "}",
            "",
            `export class ${className} {`,
            "  readonly name: string;",
            "  readonly description: string;",
            "  private history: Message[] = [];",
            "  private maxHistory: number;",
            "  private variables = new Map<string, unknown>();",
            "",
            `  constructor(maxHistory = ${maxHistory}) {`,
            `    this.name = "${name}";`,
            `    this.description = "${desc || name + " — 对话上下文"}";`,
            "    this.maxHistory = maxHistory;",
            "  }",
            "",
            "  addMessage(role: Role, content: string, metadata?: Record<string, unknown>): void {",
            "    this.history.push({ role, content, timestamp: Date.now(), metadata });",
            "    if (this.history.length > this.maxHistory) {",
            "      this.history = this.history.slice(-this.maxHistory);",
            "    }",
            "  }",
            "",
            "  getHistory(limit?: number): Message[] {",
            "    return limit ? this.history.slice(-limit) : [...this.history];",
            "  }",
            "",
            "  getLastMessage(): Message | undefined {",
            "    return this.history[this.history.length - 1];",
            "  }",
            "",
            "  getMessagesByRole(role: Role): Message[] {",
            "    return this.history.filter((m) => m.role === role);",
            "  }",
            "",
            "  setVariable(key: string, value: unknown): void {",
            "    this.variables.set(key, value);",
            "  }",
            "",
            "  getVariable<T = unknown>(key: string): T | undefined {",
            "    return this.variables.get(key) as T | undefined;",
            "  }",
            "",
            "  clearHistory(): void {",
            "    this.history = [];",
            "  }",
            "",
            "  summary(): string {",
            "    return [",
            "      `对话上下文: ${this.name}`,",
            "      `消息数: ${this.history.length}`,",
            "      `变量数: ${this.variables.size}`,",
            "    ].join(\", \");",
            "  }",
            "",
            "  toJSON() {",
            "    return {",
            "      name: this.name,",
            "      history: this.history,",
            "      variables: Object.fromEntries(this.variables),",
            "    };",
            "  }",
            "}",
            "",
            `export default ${className};`,
            "",
          ].join("\n"),
        },
      ];
    },
  },

  {
    name: "task",
    description: "任务上下文 — 任务执行状态与结果追踪",
    category: "context",
    variables: [
      { name: "name", description: "上下文名称", type: "string", required: true },
      { name: "description", description: "上下文描述", type: "string", default: "" },
    ],
    render(v) {
      const { name, id, className, desc } = vars(v);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            "export type TaskStatus = \"pending\" | \"running\" | \"completed\" | \"failed\" | \"cancelled\";",
            "",
            "export interface TaskEntry {",
            "  id: string;",
            "  name: string;",
            "  status: TaskStatus;",
            "  input?: unknown;",
            "  output?: unknown;",
            "  error?: string;",
            "  startedAt?: number;",
            "  completedAt?: number;",
            "}",
            "",
            `export class ${className} {`,
            "  readonly name: string;",
            "  readonly description: string;",
            "  private tasks = new Map<string, TaskEntry>();",
            "  private globalData = new Map<string, unknown>();",
            "",
            "  constructor() {",
            `    this.name = "${name}";`,
            `    this.description = "${desc || name + " — 任务上下文"}";`,
            "  }",
            "",
            "  createTask(id: string, name: string, input?: unknown): TaskEntry {",
            '    const task: TaskEntry = { id, name, status: "pending", input };',
            "    this.tasks.set(id, task);",
            "    return task;",
            "  }",
            "",
            "  startTask(id: string): void {",
            "    const task = this.tasks.get(id);",
            '    if (task) { task.status = "running"; task.startedAt = Date.now(); }',
            "  }",
            "",
            "  completeTask(id: string, output?: unknown): void {",
            "    const task = this.tasks.get(id);",
            "    if (task) {",
            '      task.status = "completed";',
            "      task.output = output;",
            "      task.completedAt = Date.now();",
            "    }",
            "  }",
            "",
            "  failTask(id: string, error: string): void {",
            "    const task = this.tasks.get(id);",
            "    if (task) {",
            '      task.status = "failed";',
            "      task.error = error;",
            "      task.completedAt = Date.now();",
            "    }",
            "  }",
            "",
            "  getTask(id: string): TaskEntry | undefined {",
            "    return this.tasks.get(id);",
            "  }",
            "",
            "  getTasksByStatus(status: TaskStatus): TaskEntry[] {",
            "    return Array.from(this.tasks.values()).filter((t) => t.status === status);",
            "  }",
            "",
            "  set(key: string, value: unknown): void {",
            "    this.globalData.set(key, value);",
            "  }",
            "",
            "  get<T = unknown>(key: string): T | undefined {",
            "    return this.globalData.get(key) as T | undefined;",
            "  }",
            "",
            "  summary(): string {",
            "    const counts = { pending: 0, running: 0, completed: 0, failed: 0, cancelled: 0 };",
            "    for (const t of this.tasks.values()) counts[t.status]++;",
            "    return `任务上下文 ${this.name}: ` +",
            "      Object.entries(counts).map(([k, v]) => `${k}=${v}`).join(\", \");",
            "  }",
            "}",
            "",
            `export default ${className};`,
            "",
          ].join("\n"),
        },
      ];
    },
  },
];
