import type { Template } from "../types";
import { toKebabCase, toPascalCase } from "../utils";

function vars(v: Record<string, unknown>) {
  const name = String(v.name ?? "my-skill");
  const id = toKebabCase(name);
  const className = toPascalCase(name) + "Skill";
  const desc = String(v.description ?? "");
  const version = String(v.version ?? "0.1.0");
  return { name, id, className, desc, version };
}

export const skillTemplates: Template[] = [
  {
    name: "basic",
    description: "基础技能 — 可复用的工具集合",
    category: "skill",
    variables: [
      { name: "name", description: "技能名称", type: "string", required: true },
      { name: "description", description: "技能描述", type: "string", default: "" },
      { name: "version", description: "版本号", type: "string", default: "0.1.0" },
    ],
    render(v) {
      const { name, id, className, desc, version } = vars(v);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            'import type { AgentTool } from "@mozi/core";',
            "",
            "export interface SkillMeta {",
            "  name: string;",
            "  description: string;",
            "  version: string;",
            "  tags: string[];",
            "}",
            "",
            "export interface Skill {",
            "  meta: SkillMeta;",
            "  tools: AgentTool[];",
            "  setup?(): Promise<void>;",
            "  teardown?(): Promise<void>;",
            "}",
            "",
            `export class ${className} implements Skill {`,
            "  meta: SkillMeta = {",
            `    name: "${name}",`,
            `    description: "${desc || name + " 技能"}",`,
            `    version: "${version}",`,
            "    tags: [],",
            "  };",
            "",
            "  tools: AgentTool[] = [",
            "    {",
            `      name: "${id}-execute",`,
            '      description: "执行技能主操作",',
            "      parameters: {",
            '        input: { type: "string", description: "输入数据" },',
            "      },",
            "      execute: async (params) => {",
            "        const input = params.input as string;",
            "        return this.process(input);",
            "      },",
            "    },",
            "  ];",
            "",
            "  private process(input: string): Record<string, unknown> {",
            "    // TODO: 实现技能逻辑",
            "    return { input, processed: true };",
            "  }",
            "}",
            "",
            `export default new ${className}();`,
            "",
          ].join("\n"),
        },
      ];
    },
  },

  {
    name: "api",
    description: "API 调用技能 — 封装外部 API 为工具",
    category: "skill",
    variables: [
      { name: "name", description: "技能名称", type: "string", required: true },
      { name: "description", description: "技能描述", type: "string", default: "" },
      { name: "baseUrl", description: "API 基础 URL", type: "string", default: "https://api.example.com" },
      { name: "version", description: "版本号", type: "string", default: "0.1.0" },
    ],
    render(v) {
      const { name, id, className, desc, version } = vars(v);
      const baseUrl = String(v.baseUrl ?? "https://api.example.com");
      return [
        {
          path: `${id}/index.ts`,
          content: [
            'import type { AgentTool } from "@mozi/core";',
            "",
            "interface ApiSkillConfig {",
            "  baseUrl: string;",
            "  headers?: Record<string, string>;",
            "  timeout?: number;",
            "}",
            "",
            `export class ${className} {`,
            "  private config: ApiSkillConfig;",
            "",
            "  constructor(config?: Partial<ApiSkillConfig>) {",
            "    this.config = {",
            `      baseUrl: config?.baseUrl ?? "${baseUrl}",`,
            "      headers: { \"Content-Type\": \"application/json\", ...config?.headers },",
            "      timeout: config?.timeout ?? 10000,",
            "    };",
            "  }",
            "",
            "  get meta() {",
            "    return {",
            `      name: "${name}",`,
            `      description: "${desc || name + " — API 调用技能"}",`,
            `      version: "${version}",`,
            '      tags: ["api"],',
            "    };",
            "  }",
            "",
            "  get tools(): AgentTool[] {",
            "    return [",
            "      {",
            `        name: "${id}-get",`,
            '        description: "GET 请求",',
            "        parameters: {",
            '          path: { type: "string", description: "API 路径" },',
            "        },",
            "        execute: async (params) => this.get(params.path as string),",
            "      },",
            "      {",
            `        name: "${id}-post",`,
            '        description: "POST 请求",',
            "        parameters: {",
            '          path: { type: "string", description: "API 路径" },',
            '          body: { type: "string", description: "请求体 (JSON)" },',
            "        },",
            "        execute: async (params) => {",
            "          const body = JSON.parse(params.body as string);",
            "          return this.post(params.path as string, body);",
            "        },",
            "      },",
            "    ];",
            "  }",
            "",
            "  private async get(path: string): Promise<unknown> {",
            "    const res = await fetch(`${this.config.baseUrl}${path}`, {",
            '      method: "GET",',
            "      headers: this.config.headers,",
            "      signal: AbortSignal.timeout(this.config.timeout!),",
            "    });",
            "    return res.json();",
            "  }",
            "",
            "  private async post(path: string, body: unknown): Promise<unknown> {",
            "    const res = await fetch(`${this.config.baseUrl}${path}`, {",
            '      method: "POST",',
            "      headers: this.config.headers,",
            "      body: JSON.stringify(body),",
            "      signal: AbortSignal.timeout(this.config.timeout!),",
            "    });",
            "    return res.json();",
            "  }",
            "}",
            "",
            `export default new ${className}();`,
            "",
          ].join("\n"),
        },
      ];
    },
  },

  {
    name: "transform",
    description: "数据转换技能 — 数据格式化与转换工具集",
    category: "skill",
    variables: [
      { name: "name", description: "技能名称", type: "string", required: true },
      { name: "description", description: "技能描述", type: "string", default: "" },
      { name: "version", description: "版本号", type: "string", default: "0.1.0" },
    ],
    render(v) {
      const { name, id, className, desc, version } = vars(v);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            'import type { AgentTool } from "@mozi/core";',
            "",
            `export class ${className} {`,
            "  get meta() {",
            "    return {",
            `      name: "${name}",`,
            `      description: "${desc || name + " — 数据转换技能"}",`,
            `      version: "${version}",`,
            '      tags: ["transform", "data"],',
            "    };",
            "  }",
            "",
            "  get tools(): AgentTool[] {",
            "    return [",
            "      {",
            `        name: "${id}-json-to-csv",`,
            '        description: "JSON 数组转 CSV",',
            "        parameters: {",
            '          json: { type: "string", description: "JSON 数组字符串" },',
            "        },",
            "        execute: async (params) => {",
            "          const data = JSON.parse(params.json as string) as Record<string, unknown>[];",
            "          if (!data.length) return \"\";",
            "          const headers = Object.keys(data[0]);",
            "          const rows = data.map((r) => headers.map((h) => String(r[h] ?? \"\")).join(\",\"));",
            '          return [headers.join(","), ...rows].join("\\n");',
            "        },",
            "      },",
            "      {",
            `        name: "${id}-flatten",`,
            '        description: "扁平化嵌套 JSON 对象",',
            "        parameters: {",
            '          json: { type: "string", description: "嵌套 JSON 字符串" },',
            '          separator: { type: "string", description: "键分隔符" },',
            "        },",
            "        execute: async (params) => {",
            "          const obj = JSON.parse(params.json as string);",
            '          const sep = (params.separator as string) ?? ".";',
            "          return this.flatten(obj, sep);",
            "        },",
            "      },",
            "      {",
            `        name: "${id}-pick-fields",`,
            '        description: "选取指定字段",',
            "        parameters: {",
            '          json: { type: "string", description: "JSON 字符串" },',
            '          fields: { type: "string", description: "逗号分隔的字段列表" },',
            "        },",
            "        execute: async (params) => {",
            "          const obj = JSON.parse(params.json as string);",
            '          const fields = (params.fields as string).split(",").map((f) => f.trim());',
            "          if (Array.isArray(obj)) {",
            "            return obj.map((item) =>",
            "              Object.fromEntries(fields.filter((f) => f in item).map((f) => [f, item[f]])),",
            "            );",
            "          }",
            "          return Object.fromEntries(fields.filter((f) => f in obj).map((f) => [f, obj[f]]));",
            "        },",
            "      },",
            "    ];",
            "  }",
            "",
            "  private flatten(",
            "    obj: Record<string, unknown>,",
            "    separator: string,",
            '    prefix = "",',
            "  ): Record<string, unknown> {",
            "    const result: Record<string, unknown> = {};",
            "    for (const [key, value] of Object.entries(obj)) {",
            "      const newKey = prefix ? `${prefix}${separator}${key}` : key;",
            "      if (value && typeof value === \"object\" && !Array.isArray(value)) {",
            "        Object.assign(result, this.flatten(value as Record<string, unknown>, separator, newKey));",
            "      } else {",
            "        result[newKey] = value;",
            "      }",
            "    }",
            "    return result;",
            "  }",
            "}",
            "",
            `export default new ${className}();`,
            "",
          ].join("\n"),
        },
      ];
    },
  },
];
