import type { Template } from "../types";
import { toKebabCase } from "../utils";

function vars(v: Record<string, unknown>) {
  const name = String(v.name ?? "my-workflow");
  const id = toKebabCase(name);
  const desc = String(v.description ?? "");
  const timeout = Number(v.timeout ?? 30000);
  return { name, id, desc, timeout };
}

export const workflowTemplates: Template[] = [
  {
    name: "sequential",
    description: "顺序工作流 — 节点按顺序依次执行",
    category: "workflow",
    variables: [
      { name: "name", description: "工作流名称", type: "string", required: true },
      { name: "description", description: "工作流描述", type: "string", default: "" },
      { name: "timeout", description: "超时时间 (ms)", type: "number", default: 30000 },
    ],
    render(v) {
      const { name, id, desc, timeout } = vars(v);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            'import { NodeType } from "@mozi/core";',
            'import type { WorkflowDefinition, NodeHandler } from "@mozi/core";',
            "",
            "const step1: NodeHandler = async (ctx) => {",
            '  ctx.set("step1Result", "处理完成");',
            '  return ctx.get("step1Result");',
            "};",
            "",
            "const step2: NodeHandler = async (ctx) => {",
            '  const prev = ctx.get<string>("step1Result");',
            "  return `上一步结果: ${prev}`;",
            "};",
            "",
            "const definition: WorkflowDefinition = {",
            `  id: "${id}",`,
            `  name: "${name}",`,
            `  description: "${desc || name + " — 顺序工作流"}",`,
            `  timeout: ${timeout},`,
            "  nodes: [",
            '    { id: "start", type: NodeType.START, name: "开始" },',
            '    { id: "step1", type: NodeType.TASK, name: "步骤一", handler: step1 },',
            '    { id: "step2", type: NodeType.TASK, name: "步骤二", handler: step2 },',
            '    { id: "end", type: NodeType.END, name: "结束" },',
            "  ],",
            "  edges: [",
            '    { from: "start", to: "step1" },',
            '    { from: "step1", to: "step2" },',
            '    { from: "step2", to: "end" },',
            "  ],",
            "};",
            "",
            "export default definition;",
            "",
          ].join("\n"),
        },
      ];
    },
  },

  {
    name: "parallel",
    description: "并行工作流 — 多节点并行执行后汇聚",
    category: "workflow",
    variables: [
      { name: "name", description: "工作流名称", type: "string", required: true },
      { name: "description", description: "工作流描述", type: "string", default: "" },
      { name: "timeout", description: "超时时间 (ms)", type: "number", default: 60000 },
    ],
    render(v) {
      const { name, id, desc, timeout } = vars(v);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            'import { NodeType } from "@mozi/core";',
            'import type { WorkflowDefinition, NodeHandler } from "@mozi/core";',
            "",
            "const fetchData: NodeHandler = async (ctx) => {",
            '  ctx.set("data", { items: [1, 2, 3] });',
            '  return ctx.get("data");',
            "};",
            "",
            "const analyzeData: NodeHandler = async (ctx) => {",
            '  ctx.set("analysis", { score: 0.95 });',
            '  return ctx.get("analysis");',
            "};",
            "",
            "const mergeResults: NodeHandler = async (ctx) => {",
            "  return {",
            '    data: ctx.get("data"),',
            '    analysis: ctx.get("analysis"),',
            "  };",
            "};",
            "",
            "const definition: WorkflowDefinition = {",
            `  id: "${id}",`,
            `  name: "${name}",`,
            `  description: "${desc || name + " — 并行工作流"}",`,
            `  timeout: ${timeout},`,
            "  nodes: [",
            '    { id: "start", type: NodeType.START, name: "开始" },',
            '    { id: "fetch", type: NodeType.TASK, name: "获取数据", handler: fetchData },',
            '    { id: "analyze", type: NodeType.TASK, name: "分析数据", handler: analyzeData },',
            '    { id: "parallel", type: NodeType.PARALLEL, name: "并行执行" },',
            '    { id: "merge", type: NodeType.TASK, name: "合并结果", handler: mergeResults },',
            '    { id: "end", type: NodeType.END, name: "结束" },',
            "  ],",
            "  edges: [",
            '    { from: "start", to: "parallel" },',
            '    { from: "parallel", to: "fetch" },',
            '    { from: "parallel", to: "analyze" },',
            '    { from: "fetch", to: "merge" },',
            '    { from: "analyze", to: "merge" },',
            '    { from: "merge", to: "end" },',
            "  ],",
            "};",
            "",
            "export default definition;",
            "",
          ].join("\n"),
        },
      ];
    },
  },

  {
    name: "conditional",
    description: "条件工作流 — 基于条件分支执行不同路径",
    category: "workflow",
    variables: [
      { name: "name", description: "工作流名称", type: "string", required: true },
      { name: "description", description: "工作流描述", type: "string", default: "" },
    ],
    render(v) {
      const { name, id, desc } = vars(v);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            'import { NodeType } from "@mozi/core";',
            'import type { WorkflowDefinition, NodeHandler } from "@mozi/core";',
            "",
            "const validate: NodeHandler = async (ctx) => {",
            "  const input = ctx.get<Record<string, unknown>>(\"input\") ?? {};",
            '  const isValid = Boolean(input.value);',
            '  ctx.set("isValid", isValid);',
            "  return isValid;",
            "};",
            "",
            "const onSuccess: NodeHandler = async (ctx) => {",
            '  return { status: "success", data: ctx.get("input") };',
            "};",
            "",
            "const onFailure: NodeHandler = async (ctx) => {",
            '  return { status: "failed", reason: "验证未通过" };',
            "};",
            "",
            "const definition: WorkflowDefinition = {",
            `  id: "${id}",`,
            `  name: "${name}",`,
            `  description: "${desc || name + " — 条件工作流"}",`,
            "  nodes: [",
            '    { id: "start", type: NodeType.START, name: "开始" },',
            '    { id: "validate", type: NodeType.TASK, name: "数据验证", handler: validate },',
            "    {",
            '      id: "check",',
            '      type: NodeType.CONDITION,',
            '      name: "条件判断",',
            '      condition: async (ctx) => ctx.get<boolean>("isValid") === true,',
            "    },",
            '    { id: "success", type: NodeType.TASK, name: "成功处理", handler: onSuccess },',
            '    { id: "failure", type: NodeType.TASK, name: "失败处理", handler: onFailure },',
            '    { id: "end", type: NodeType.END, name: "结束" },',
            "  ],",
            "  edges: [",
            '    { from: "start", to: "validate" },',
            '    { from: "validate", to: "check" },',
            '    { from: "check", to: "success", label: "通过" },',
            '    { from: "check", to: "failure", label: "拒绝" },',
            '    { from: "success", to: "end" },',
            '    { from: "failure", to: "end" },',
            "  ],",
            "};",
            "",
            "export default definition;",
            "",
          ].join("\n"),
        },
      ];
    },
  },

  {
    name: "pipeline",
    description: "数据管道工作流 — ETL 式数据处理流水线",
    category: "workflow",
    variables: [
      { name: "name", description: "工作流名称", type: "string", required: true },
      { name: "description", description: "工作流描述", type: "string", default: "" },
      { name: "timeout", description: "超时时间 (ms)", type: "number", default: 120000 },
    ],
    render(v) {
      const { name, id, desc, timeout } = vars(v);
      return [
        {
          path: `${id}/index.ts`,
          content: [
            'import { NodeType } from "@mozi/core";',
            'import type { WorkflowDefinition, NodeHandler } from "@mozi/core";',
            "",
            "const extract: NodeHandler = async (ctx) => {",
            "  // TODO: 从数据源提取原始数据",
            '  const rawData = [{ id: 1, value: "raw" }];',
            '  ctx.set("rawData", rawData);',
            "  return rawData;",
            "};",
            "",
            "const transform: NodeHandler = async (ctx) => {",
            "  const raw = ctx.get<Array<Record<string, unknown>>>(\"rawData\") ?? [];",
            "  const transformed = raw.map((r) => ({",
            "    ...r,",
            '    value: String(r.value).toUpperCase(),',
            "    processedAt: Date.now(),",
            "  }));",
            '  ctx.set("transformed", transformed);',
            "  return transformed;",
            "};",
            "",
            "const load: NodeHandler = async (ctx) => {",
            "  const data = ctx.get(\"transformed\");",
            "  // TODO: 写入目标存储",
            "  return { loaded: true, count: Array.isArray(data) ? data.length : 0 };",
            "};",
            "",
            "const definition: WorkflowDefinition = {",
            `  id: "${id}",`,
            `  name: "${name}",`,
            `  description: "${desc || name + " — ETL 数据管道"}",`,
            `  timeout: ${timeout},`,
            "  nodes: [",
            '    { id: "start", type: NodeType.START, name: "开始" },',
            '    { id: "extract", type: NodeType.TASK, name: "提取 (Extract)", handler: extract },',
            '    { id: "transform", type: NodeType.TASK, name: "转换 (Transform)", handler: transform },',
            '    { id: "load", type: NodeType.TASK, name: "加载 (Load)", handler: load },',
            '    { id: "end", type: NodeType.END, name: "结束" },',
            "  ],",
            "  edges: [",
            '    { from: "start", to: "extract" },',
            '    { from: "extract", to: "transform" },',
            '    { from: "transform", to: "load" },',
            '    { from: "load", to: "end" },',
            "  ],",
            "};",
            "",
            "export default definition;",
            "",
          ].join("\n"),
        },
      ];
    },
  },
];
