apiVersion: v1
kind: Secret
metadata:
  name: mozi-secret
  namespace: mozi
  labels:
    app.kubernetes.io/part-of: mozi
type: Opaque
data:
  MOZI_JWT_SECRET: Y2hhbmdlbWU=
  MOZI_DB_PASSWORD: Y2hhbmdlbWU=
  MOZI_GITHUB_CLIENT_ID: Y2hhbmdlbWU=
  MOZI_GITHUB_CLIENT_SECRET: Y2hhbmdlbWU=
  MOZI_MINIO_ACCESS_KEY: Y2hhbmdlbWU=
  MOZI_MINIO_SECRET_KEY: Y2hhbmdlbWU=
