"""add_workspace_path_column

Revision ID: 1842f1ac7aae
Revises: bdce3646bd28
Create Date: 2026-03-30 13:32:54.673854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1842f1ac7aae'
down_revision: Union[str, None] = 'bdce3646bd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'path')
    # ### end Alembic commands ###
