"""add_user_active_workspace_id

Revision ID: 251988f46ee0
Revises: 1842f1ac7aae
Create Date: 2026-03-30 14:08:27.210905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251988f46ee0'
down_revision: Union[str, None] = '1842f1ac7aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_workspace_id', sa.String(length=21), nullable=True))
    op.create_foreign_key(None, 'users', 'workspaces', ['active_workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_workspace_id')
    # ### end Alembic commands ###
