apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: mozi
  labels:
    app.kubernetes.io/name: agent-service
    app.kubernetes.io/part-of: mozi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: agent-service
    app.kubernetes.io/part-of: mozi
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
