apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mozi
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: mozi
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: mozi
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
